name: Huizenbot

on:
  schedule:
    - cron: "*/5 * * * *"          # elke 5 min (UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure data dir exists          # ⬅︎ nieuw
        run: mkdir -p data

      - name: Download seen.db
        id: get_db
        uses: actions/download-artifact@v4
        with:
          name: seen-db
          path: data
        continue-on-error: true      # géén fout als hij er nog niet is

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scraper once
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:        ${{ secrets.CHAT_ID }}
        run: |
          mkdir -p data                     # zorg dat mapje bestaat
          python src/run_once.py

      # 2 ── upload / overschrijf de database
      - name: Upload seen.db
        if: always()                        # voer ook uit als er geen nieuwe woningen waren
        uses: actions/upload-artifact@v4
        with:
          name: seen-db
          path: data/seen.db
          retention-days: 90
