name: mariawoonbot

on:
  schedule:
    - cron: "*/5 * * * *"     # elke 5 min
  workflow_dispatch:           # handmatig starten kan ook

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run scraper once
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:        ${{ secrets.CHAT_ID }}
        run: python src/run_once.py
