name: mariawoonbot

on:
  schedule:
    - cron: "*/5 * * * *"      # elke 5 min (UTC, kan 1‑10 min variëren)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # — 1.  DB terugzetten (indien aanwezig) —
      - name: Restore DB
        id: restore_db
        uses: actions/cache@v4
        with:
          path: data/seen.db
          key: huizenbot-db          # constant key  → 1 cache voor alle runs
        continue-on-error: true      # eerste run heeft nog niets

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scraper once
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:        ${{ secrets.CHAT_ID }}
        run: |
          mkdir -p data          # verzeker mapje voor het eerst
          python src/run_once.py

      # — 2.  DB opslaan voor volgende run —
      - name: Save DB
        if: always()             # ook uitvoeren als er geen nieuwe woningen waren
        uses: actions/cache/save@v4
        with:
          path: data/seen.db
          key: huizenbot-db
